[tracing]
exporter = "none" #otlp

[storage]
path = "dev.db"

[[enhancement]]
type = "pwd"

[[enhancement]]
type = "tag-add"
check = "pwd"
condition = "prefix"
[enhancement.values]
"/home/andy/dev/projects/hirsi" = [ "hirsi" ]

[[pipe]]
name = "default"

[[pipe.renderer]]
type = "obsidian"
path = "obsidian-dev/hirsi-dev"
titles = ["gha"]
