[storage]
path = "relative/file.db"


[[enhancement]]
type = "pwd"

# [[enhancement]]
# type = "conditional-tag"
# condition = "pwd ~= /projects/secret"
# add = [ "hidden" ]
# remove= ["other"]



[[pipe]]
name = "only-secret"

[[pipe.filter]]
type = "tag-with-prefix"
tag = "pwd"
prefix = "/home/andy/dev/secret"

[[pipe.renderer]]
type = "log"
path = "/home/andy/dev/secret/log-plain"


[[pipe]]
name = "not-secret"

[[pipe.filter]]
type = "tag-without-prefix"
tag = "pwd"
prefix = "/home/andy/dev/secret"

[[pipe.renderer]]
type = "log"
path = "/home/andy/log"

[[pipe.renderer]]
type = "obsidian"
path = "/home/andy/dev/projects/hirsi/obsidian-dev/hirsi-dev"
titles = ["teamcity", "portal", "things"]
